import { useParams } from "react-router-dom";
import Page from "../components/Page"
import NavBar from "../components/NavBar";
import { formatTime } from "../utils/helpers";

const BookmarkPage = () => {
  const { word } = useParams();
  return (
    <Page>
      <NavBar showMenu/>
      <div>
        <h1 className="text-5xl">{word}</h1>
        <div className="card card-sm bg-base-100 border border-base-300">
          <div className="card-body flex flex-row gap-4">
            <img src={`https://img.youtube.com/vi/2lyygzfl1ZY/mqdefault.jpg`} alt="thumbnail" className="rounded-lg w-80"/>
            <div className="flex flex-col gap-4">
              <h1 className="text-lg">FIFA World Cup kicks off and Football Australia makes major announcement</h1>
              <div className="flex flex-row border border-base-300 rounded-lg p-4 gap-4">
                <div className={`text-neutral-400 bg-neutral-100 rounded-full px-2`}>
                  {formatTime(0)}
                </div>
                <blockquote>a luminous time</blockquote>
              </div>
              <div>
                <p className="uppercase">Cultural Insight</p>
                <p>A cultural insight generated by AI</p>
              </div>
            </div>
            <div className="flex items-center ml-auto">
              <button className="btn btn-circle btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="size-6">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </Page>
  )
}

export default BookmarkPage